{{- if .Values.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-secret-docker
  namespace: {{ .Release.Namespace | quote }}
  labels: {{ include "common.labels.standard" . | nindent 4 }}
data:
  .dockerconfigjson: {{ .Values.dockerConfig }}
type: kubernetes.io/dockerconfigjson
{{- end }}
